[2025-03-31T00:00:02.752+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T00:00:02.774+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_data.create_index scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T00:00:02.783+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_data.create_index scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T00:00:02.784+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-31T00:00:02.795+0000] {taskinstance.py:2890} INFO - Executing <Task(SQLExecuteQueryOperator): create_index> on 2025-03-30 00:00:00+00:00
[2025-03-31T00:00:02.804+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=691) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-31T00:00:02.803+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'sales_data', 'create_index', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/sales.py', '--cfg-path', '/tmp/tmptk9vdi1k']
[2025-03-31T00:00:02.805+0000] {standard_task_runner.py:72} INFO - Started process 692 to run task
[2025-03-31T00:00:02.805+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask create_index
[2025-03-31T00:00:02.843+0000] {task_command.py:467} INFO - Running <TaskInstance: sales_data.create_index scheduled__2025-03-30T00:00:00+00:00 [running]> on host e52df2a83a37
[2025-03-31T00:00:02.897+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sales_data' AIRFLOW_CTX_TASK_ID='create_index' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-03-31T00:00:02.897+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T00:00:02.905+0000] {sql.py:295} INFO - Executing: 
        create index if not exists raw_sales_product_index on raw.sales ("ProductID");
        create index if not exists raw_sales_retailer_index on raw.sales ("RetailerID");
        create index if not exists raw_sales_location_index on raw.sales ("Location");
        create index if not exists raw_sales_date_index on raw.sales ("Date");
        
[2025-03-31T00:00:02.905+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (LocalFilesystemBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 317, in get_connection
    if conn_id in self._local_connections:
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 314, in _local_connections
    return load_connections_dict(self.connections_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 266, in load_connections_dict
    secrets: dict[str, Any] = _parse_secret_file(file_path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 163, in _parse_secret_file
    raise AirflowException(
airflow.exceptions.AirflowException: File /opt/secrets/connections.yaml was not found. Check the configuration of your Secrets backend.
[2025-03-31T00:00:02.916+0000] {base.py:84} INFO - Retrieving connection 'db'
[2025-03-31T00:00:02.918+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (LocalFilesystemBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 317, in get_connection
    if conn_id in self._local_connections:
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 314, in _local_connections
    return load_connections_dict(self.connections_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 266, in load_connections_dict
    secrets: dict[str, Any] = _parse_secret_file(file_path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/local_filesystem.py", line 163, in _parse_secret_file
    raise AirflowException(
airflow.exceptions.AirflowException: File /opt/secrets/connections.yaml was not found. Check the configuration of your Secrets backend.
[2025-03-31T00:00:02.928+0000] {base.py:84} INFO - Retrieving connection 'db'
[2025-03-31T00:00:02.935+0000] {sql.py:511} INFO - Running statement: 
        create index if not exists raw_sales_product_index on raw.sales ("ProductID");
        create index if not exists raw_sales_retailer_index on raw.sales ("RetailerID");
        create index if not exists raw_sales_location_index on raw.sales ("Location");
        create index if not exists raw_sales_date_index on raw.sales ("Date");
        , parameters: None
[2025-03-31T00:00:02.941+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py:470 DeprecationWarning: Import of fetch_all_handler from the 'airflow.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from 'airflow.providers.common.sql.hooks.handlers'.
[2025-03-31T00:00:02.942+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py:471 DeprecationWarning: Import of return_single_query_results from the 'airflow.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from 'airflow.providers.common.sql.hooks.handlers'.
[2025-03-31T00:00:02.943+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py:486 DeprecationWarning: Import of return_single_query_results from the 'airflow.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from 'airflow.providers.common.sql.hooks.handlers'.
[2025-03-31T00:00:02.943+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py:311 DeprecationWarning: Import of return_single_query_results from the 'airflow.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from 'airflow.providers.common.sql.hooks.handlers'.
[2025-03-31T00:00:02.954+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T00:00:02.954+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=sales_data, task_id=create_index, run_id=scheduled__2025-03-30T00:00:00+00:00, execution_date=20250330T000000, start_date=20250331T000002, end_date=20250331T000002
[2025-03-31T00:00:02.980+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T00:00:03.001+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-31T00:00:03.002+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
