[2025-03-30T23:37:15.638+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T23:37:15.658+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_data.build_dbt manual__2025-03-30T23:35:43.744902+00:00 [queued]>
[2025-03-30T23:37:15.663+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_data.build_dbt manual__2025-03-30T23:35:43.744902+00:00 [queued]>
[2025-03-30T23:37:15.663+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-03-30T23:37:15.671+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): build_dbt> on 2025-03-30 23:35:43.744902+00:00
[2025-03-30T23:37:15.678+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'sales_data', 'build_dbt', 'manual__2025-03-30T23:35:43.744902+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/sales.py', '--cfg-path', '/tmp/tmp32d2yslp']
[2025-03-30T23:37:15.680+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=369) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T23:37:15.681+0000] {standard_task_runner.py:105} INFO - Job 68: Subtask build_dbt
[2025-03-30T23:37:15.681+0000] {standard_task_runner.py:72} INFO - Started process 370 to run task
[2025-03-30T23:37:15.726+0000] {task_command.py:467} INFO - Running <TaskInstance: sales_data.build_dbt manual__2025-03-30T23:35:43.744902+00:00 [running]> on host dce992005bb5
[2025-03-30T23:37:15.801+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sales_data' AIRFLOW_CTX_TASK_ID='build_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T23:35:43.744902+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T23:35:43.744902+00:00'
[2025-03-30T23:37:15.802+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T23:37:15.814+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-30T23:37:15.814+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd ${AIRFLOW_HOME}/dags/dbt/hostaway_tht && dbt build --profiles-dir ./..']
[2025-03-30T23:37:15.823+0000] {subprocess.py:99} INFO - Output:
[2025-03-30T23:37:17.519+0000] {subprocess.py:106} INFO - [0m23:37:17  Running with dbt=1.9.3
[2025-03-30T23:37:17.907+0000] {subprocess.py:106} INFO - [0m23:37:17  Registered adapter: postgres=1.9.0
[2025-03-30T23:37:18.487+0000] {subprocess.py:106} INFO - [0m23:37:18  Found 5 models, 13 data tests, 1 source, 434 macros
[2025-03-30T23:37:18.490+0000] {subprocess.py:106} INFO - [0m23:37:18
[2025-03-30T23:37:18.491+0000] {subprocess.py:106} INFO - [0m23:37:18  Concurrency: 1 threads (target='dev')
[2025-03-30T23:37:18.491+0000] {subprocess.py:106} INFO - [0m23:37:18
[2025-03-30T23:37:18.643+0000] {subprocess.py:106} INFO - [0m23:37:18  1 of 18 START sql view model staging.staging__sales ............................ [RUN]
[2025-03-30T23:37:18.724+0000] {subprocess.py:106} INFO - [0m23:37:18  1 of 18 OK created sql view model staging.staging__sales ....................... [[32mCREATE VIEW[0m in 0.08s]
[2025-03-30T23:37:18.725+0000] {subprocess.py:106} INFO - [0m23:37:18  2 of 18 START test accepted_values_staging__sales_channel__Offline__Online ..... [RUN]
[2025-03-30T23:37:18.763+0000] {subprocess.py:106} INFO - [0m23:37:18  2 of 18 PASS accepted_values_staging__sales_channel__Offline__Online ........... [[32mPASS[0m in 0.04s]
[2025-03-30T23:37:18.764+0000] {subprocess.py:106} INFO - [0m23:37:18  3 of 18 START test not_null_staging__sales_id .................................. [RUN]
[2025-03-30T23:37:18.785+0000] {subprocess.py:106} INFO - [0m23:37:18  3 of 18 PASS not_null_staging__sales_id ........................................ [[32mPASS[0m in 0.02s]
[2025-03-30T23:37:18.786+0000] {subprocess.py:106} INFO - [0m23:37:18  4 of 18 START test not_null_staging__sales_product_id .......................... [RUN]
[2025-03-30T23:37:18.803+0000] {subprocess.py:106} INFO - [0m23:37:18  4 of 18 PASS not_null_staging__sales_product_id ................................ [[32mPASS[0m in 0.02s]
[2025-03-30T23:37:18.805+0000] {subprocess.py:106} INFO - [0m23:37:18  5 of 18 START test not_null_staging__sales_retailer_id ......................... [RUN]
[2025-03-30T23:37:18.822+0000] {subprocess.py:106} INFO - [0m23:37:18  5 of 18 PASS not_null_staging__sales_retailer_id ............................... [[32mPASS[0m in 0.02s]
[2025-03-30T23:37:18.823+0000] {subprocess.py:106} INFO - [0m23:37:18  6 of 18 START test unique_staging__sales_id .................................... [RUN]
[2025-03-30T23:37:18.841+0000] {subprocess.py:106} INFO - [0m23:37:18  6 of 18 PASS unique_staging__sales_id .......................................... [[32mPASS[0m in 0.02s]
[2025-03-30T23:37:18.843+0000] {subprocess.py:106} INFO - [0m23:37:18  7 of 18 START sql incremental model intermediate.intermediate__dim_products .... [RUN]
[2025-03-30T23:37:18.979+0000] {subprocess.py:106} INFO - [0m23:37:18  7 of 18 OK created sql incremental model intermediate.intermediate__dim_products  [[32mINSERT 0 9[0m in 0.13s]
[2025-03-30T23:37:18.981+0000] {subprocess.py:106} INFO - [0m23:37:18  8 of 18 START sql incremental model intermediate.intermediate__dim_retailers ... [RUN]
[2025-03-30T23:37:19.027+0000] {subprocess.py:106} INFO - [0m23:37:19  8 of 18 OK created sql incremental model intermediate.intermediate__dim_retailers  [[32mINSERT 0 3[0m in 0.05s]
[2025-03-30T23:37:19.029+0000] {subprocess.py:106} INFO - [0m23:37:19  9 of 18 START sql incremental model intermediate.intermediate__fact_sales ...... [RUN]
[2025-03-30T23:37:19.073+0000] {subprocess.py:106} INFO - [0m23:37:19  9 of 18 OK created sql incremental model intermediate.intermediate__fact_sales . [[32mINSERT 0 1[0m in 0.04s]
[2025-03-30T23:37:19.074+0000] {subprocess.py:106} INFO - [0m23:37:19  10 of 18 START test not_null_intermediate__dim_products_id ..................... [RUN]
[2025-03-30T23:37:19.097+0000] {subprocess.py:106} INFO - [0m23:37:19  10 of 18 PASS not_null_intermediate__dim_products_id ........................... [[32mPASS[0m in 0.02s]
[2025-03-30T23:37:19.099+0000] {subprocess.py:106} INFO - [0m23:37:19  11 of 18 START test unique_intermediate__dim_products_id ....................... [RUN]
[2025-03-30T23:37:19.121+0000] {subprocess.py:106} INFO - [0m23:37:19  11 of 18 PASS unique_intermediate__dim_products_id ............................. [[32mPASS[0m in 0.02s]
[2025-03-30T23:37:19.123+0000] {subprocess.py:106} INFO - [0m23:37:19  12 of 18 START test not_null_intermediate__dim_retailers_id .................... [RUN]
[2025-03-30T23:37:19.144+0000] {subprocess.py:106} INFO - [0m23:37:19  12 of 18 PASS not_null_intermediate__dim_retailers_id .......................... [[32mPASS[0m in 0.02s]
[2025-03-30T23:37:19.145+0000] {subprocess.py:106} INFO - [0m23:37:19  13 of 18 START test unique_intermediate__dim_retailers_id ...................... [RUN]
[2025-03-30T23:37:19.167+0000] {subprocess.py:106} INFO - [0m23:37:19  13 of 18 PASS unique_intermediate__dim_retailers_id ............................ [[32mPASS[0m in 0.02s]
[2025-03-30T23:37:19.168+0000] {subprocess.py:106} INFO - [0m23:37:19  14 of 18 START test not_null_intermediate__fact_sales_id ....................... [RUN]
[2025-03-30T23:37:19.190+0000] {subprocess.py:106} INFO - [0m23:37:19  14 of 18 PASS not_null_intermediate__fact_sales_id ............................. [[32mPASS[0m in 0.02s]
[2025-03-30T23:37:19.192+0000] {subprocess.py:106} INFO - [0m23:37:19  15 of 18 START test unique_intermediate__fact_sales_id ......................... [RUN]
[2025-03-30T23:37:19.210+0000] {subprocess.py:106} INFO - [0m23:37:19  15 of 18 PASS unique_intermediate__fact_sales_id ............................... [[32mPASS[0m in 0.02s]
[2025-03-30T23:37:19.212+0000] {subprocess.py:106} INFO - [0m23:37:19  16 of 18 START sql incremental model mart.sales_metrics ........................ [RUN]
[2025-03-30T23:37:19.229+0000] {subprocess.py:106} INFO - [0m23:37:19  16 of 18 ERROR creating sql incremental model mart.sales_metrics ............... [[31mERROR[0m in 0.02s]
[2025-03-30T23:37:19.231+0000] {subprocess.py:106} INFO - [0m23:37:19  17 of 18 SKIP test not_null_sales_metrics_sale_date ............................ [[33mSKIP[0m]
[2025-03-30T23:37:19.232+0000] {subprocess.py:106} INFO - [0m23:37:19  18 of 18 SKIP test unique_sales_metrics_sale_date .............................. [[33mSKIP[0m]
[2025-03-30T23:37:19.260+0000] {subprocess.py:106} INFO - [0m23:37:19
[2025-03-30T23:37:19.262+0000] {subprocess.py:106} INFO - [0m23:37:19  Finished running 4 incremental models, 13 data tests, 1 view model in 0 hours 0 minutes and 0.77 seconds (0.77s).
[2025-03-30T23:37:19.296+0000] {subprocess.py:106} INFO - [0m23:37:19
[2025-03-30T23:37:19.296+0000] {subprocess.py:106} INFO - [0m23:37:19  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[2025-03-30T23:37:19.296+0000] {subprocess.py:106} INFO - [0m23:37:19
[2025-03-30T23:37:19.297+0000] {subprocess.py:106} INFO - [0m23:37:19    Database Error in model sales_metrics (models/mart/sales_metrics.sql)
[2025-03-30T23:37:19.297+0000] {subprocess.py:106} INFO -   syntax error at or near "where"
[2025-03-30T23:37:19.297+0000] {subprocess.py:106} INFO -   LINE 25: where sale_date >= coalesce(
[2025-03-30T23:37:19.297+0000] {subprocess.py:106} INFO -            ^
[2025-03-30T23:37:19.297+0000] {subprocess.py:106} INFO - [0m23:37:19
[2025-03-30T23:37:19.298+0000] {subprocess.py:106} INFO - [0m23:37:19  Done. PASS=15 WARN=0 ERROR=1 SKIP=2 TOTAL=18
[2025-03-30T23:37:20.167+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-30T23:37:20.184+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-30T23:37:20.188+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=sales_data, task_id=build_dbt, run_id=manual__2025-03-30T23:35:43.744902+00:00, execution_date=20250330T233543, start_date=20250330T233715, end_date=20250330T233720
[2025-03-30T23:37:20.228+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T23:37:20.228+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 68 for task build_dbt (Bash command failed. The command returned a non-zero exit code 1.; 370)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-30T23:37:20.264+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T23:37:20.286+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T23:37:20.288+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
