[2025-03-30T23:36:33.251+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T23:36:33.265+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_data.build_dbt manual__2025-03-30T23:35:43.744902+00:00 [queued]>
[2025-03-30T23:36:33.270+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_data.build_dbt manual__2025-03-30T23:35:43.744902+00:00 [queued]>
[2025-03-30T23:36:33.270+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-30T23:36:33.275+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): build_dbt> on 2025-03-30 23:35:43.744902+00:00
[2025-03-30T23:36:33.284+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=323) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T23:36:33.283+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'sales_data', 'build_dbt', 'manual__2025-03-30T23:35:43.744902+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/sales.py', '--cfg-path', '/tmp/tmpko4yo90g']
[2025-03-30T23:36:33.284+0000] {standard_task_runner.py:72} INFO - Started process 324 to run task
[2025-03-30T23:36:33.285+0000] {standard_task_runner.py:105} INFO - Job 67: Subtask build_dbt
[2025-03-30T23:36:33.319+0000] {task_command.py:467} INFO - Running <TaskInstance: sales_data.build_dbt manual__2025-03-30T23:35:43.744902+00:00 [running]> on host dce992005bb5
[2025-03-30T23:36:33.370+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sales_data' AIRFLOW_CTX_TASK_ID='build_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T23:35:43.744902+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T23:35:43.744902+00:00'
[2025-03-30T23:36:33.371+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T23:36:33.379+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-30T23:36:33.380+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd ${AIRFLOW_HOME}/dags/dbt/hostaway_tht && dbt build --profiles-dir ./..']
[2025-03-30T23:36:33.388+0000] {subprocess.py:99} INFO - Output:
[2025-03-30T23:36:34.735+0000] {subprocess.py:106} INFO - [0m23:36:34  Running with dbt=1.9.3
[2025-03-30T23:36:34.874+0000] {subprocess.py:106} INFO - [0m23:36:34  Registered adapter: postgres=1.9.0
[2025-03-30T23:36:35.282+0000] {subprocess.py:106} INFO - [0m23:36:35  Found 5 models, 13 data tests, 1 source, 434 macros
[2025-03-30T23:36:35.283+0000] {subprocess.py:106} INFO - [0m23:36:35
[2025-03-30T23:36:35.284+0000] {subprocess.py:106} INFO - [0m23:36:35  Concurrency: 1 threads (target='dev')
[2025-03-30T23:36:35.284+0000] {subprocess.py:106} INFO - [0m23:36:35
[2025-03-30T23:36:35.406+0000] {subprocess.py:106} INFO - [0m23:36:35  1 of 18 START sql view model staging.staging__sales ............................ [RUN]
[2025-03-30T23:36:35.470+0000] {subprocess.py:106} INFO - [0m23:36:35  1 of 18 OK created sql view model staging.staging__sales ....................... [[32mCREATE VIEW[0m in 0.06s]
[2025-03-30T23:36:35.472+0000] {subprocess.py:106} INFO - [0m23:36:35  2 of 18 START test accepted_values_staging__sales_channel__Offline__Online ..... [RUN]
[2025-03-30T23:36:35.502+0000] {subprocess.py:106} INFO - [0m23:36:35  2 of 18 PASS accepted_values_staging__sales_channel__Offline__Online ........... [[32mPASS[0m in 0.03s]
[2025-03-30T23:36:35.503+0000] {subprocess.py:106} INFO - [0m23:36:35  3 of 18 START test not_null_staging__sales_id .................................. [RUN]
[2025-03-30T23:36:35.524+0000] {subprocess.py:106} INFO - [0m23:36:35  3 of 18 PASS not_null_staging__sales_id ........................................ [[32mPASS[0m in 0.02s]
[2025-03-30T23:36:35.525+0000] {subprocess.py:106} INFO - [0m23:36:35  4 of 18 START test not_null_staging__sales_product_id .......................... [RUN]
[2025-03-30T23:36:35.542+0000] {subprocess.py:106} INFO - [0m23:36:35  4 of 18 PASS not_null_staging__sales_product_id ................................ [[32mPASS[0m in 0.02s]
[2025-03-30T23:36:35.543+0000] {subprocess.py:106} INFO - [0m23:36:35  5 of 18 START test not_null_staging__sales_retailer_id ......................... [RUN]
[2025-03-30T23:36:35.560+0000] {subprocess.py:106} INFO - [0m23:36:35  5 of 18 PASS not_null_staging__sales_retailer_id ............................... [[32mPASS[0m in 0.02s]
[2025-03-30T23:36:35.561+0000] {subprocess.py:106} INFO - [0m23:36:35  6 of 18 START test unique_staging__sales_id .................................... [RUN]
[2025-03-30T23:36:35.578+0000] {subprocess.py:106} INFO - [0m23:36:35  6 of 18 PASS unique_staging__sales_id .......................................... [[32mPASS[0m in 0.02s]
[2025-03-30T23:36:35.580+0000] {subprocess.py:106} INFO - [0m23:36:35  7 of 18 START sql incremental model intermediate.intermediate__dim_products .... [RUN]
[2025-03-30T23:36:35.691+0000] {subprocess.py:106} INFO - [0m23:36:35  7 of 18 OK created sql incremental model intermediate.intermediate__dim_products  [[32mINSERT 0 9[0m in 0.11s]
[2025-03-30T23:36:35.692+0000] {subprocess.py:106} INFO - [0m23:36:35  8 of 18 START sql incremental model intermediate.intermediate__dim_retailers ... [RUN]
[2025-03-30T23:36:35.726+0000] {subprocess.py:106} INFO - [0m23:36:35  8 of 18 OK created sql incremental model intermediate.intermediate__dim_retailers  [[32mINSERT 0 3[0m in 0.03s]
[2025-03-30T23:36:35.727+0000] {subprocess.py:106} INFO - [0m23:36:35  9 of 18 START sql incremental model intermediate.intermediate__fact_sales ...... [RUN]
[2025-03-30T23:36:35.763+0000] {subprocess.py:106} INFO - [0m23:36:35  9 of 18 OK created sql incremental model intermediate.intermediate__fact_sales . [[32mINSERT 0 1[0m in 0.04s]
[2025-03-30T23:36:35.764+0000] {subprocess.py:106} INFO - [0m23:36:35  10 of 18 START test not_null_intermediate__dim_products_id ..................... [RUN]
[2025-03-30T23:36:35.781+0000] {subprocess.py:106} INFO - [0m23:36:35  10 of 18 PASS not_null_intermediate__dim_products_id ........................... [[32mPASS[0m in 0.02s]
[2025-03-30T23:36:35.783+0000] {subprocess.py:106} INFO - [0m23:36:35  11 of 18 START test unique_intermediate__dim_products_id ....................... [RUN]
[2025-03-30T23:36:35.802+0000] {subprocess.py:106} INFO - [0m23:36:35  11 of 18 PASS unique_intermediate__dim_products_id ............................. [[32mPASS[0m in 0.02s]
[2025-03-30T23:36:35.803+0000] {subprocess.py:106} INFO - [0m23:36:35  12 of 18 START test not_null_intermediate__dim_retailers_id .................... [RUN]
[2025-03-30T23:36:35.822+0000] {subprocess.py:106} INFO - [0m23:36:35  12 of 18 PASS not_null_intermediate__dim_retailers_id .......................... [[32mPASS[0m in 0.02s]
[2025-03-30T23:36:35.823+0000] {subprocess.py:106} INFO - [0m23:36:35  13 of 18 START test unique_intermediate__dim_retailers_id ...................... [RUN]
[2025-03-30T23:36:35.841+0000] {subprocess.py:106} INFO - [0m23:36:35  13 of 18 PASS unique_intermediate__dim_retailers_id ............................ [[32mPASS[0m in 0.02s]
[2025-03-30T23:36:35.842+0000] {subprocess.py:106} INFO - [0m23:36:35  14 of 18 START test not_null_intermediate__fact_sales_id ....................... [RUN]
[2025-03-30T23:36:35.858+0000] {subprocess.py:106} INFO - [0m23:36:35  14 of 18 PASS not_null_intermediate__fact_sales_id ............................. [[32mPASS[0m in 0.02s]
[2025-03-30T23:36:35.859+0000] {subprocess.py:106} INFO - [0m23:36:35  15 of 18 START test unique_intermediate__fact_sales_id ......................... [RUN]
[2025-03-30T23:36:35.877+0000] {subprocess.py:106} INFO - [0m23:36:35  15 of 18 PASS unique_intermediate__fact_sales_id ............................... [[32mPASS[0m in 0.02s]
[2025-03-30T23:36:35.879+0000] {subprocess.py:106} INFO - [0m23:36:35  16 of 18 START sql incremental model mart.sales_metrics ........................ [RUN]
[2025-03-30T23:36:35.901+0000] {subprocess.py:106} INFO - [0m23:36:35  16 of 18 OK created sql incremental model mart.sales_metrics ................... [[32mSELECT 33[0m in 0.02s]
[2025-03-30T23:36:35.902+0000] {subprocess.py:106} INFO - [0m23:36:35  17 of 18 START test not_null_sales_metrics_date ................................ [RUN]
[2025-03-30T23:36:35.919+0000] {subprocess.py:106} INFO - [0m23:36:35  17 of 18 ERROR not_null_sales_metrics_date ..................................... [[31mERROR[0m in 0.02s]
[2025-03-30T23:36:35.921+0000] {subprocess.py:106} INFO - [0m23:36:35  18 of 18 START test unique_sales_metrics_date .................................. [RUN]
[2025-03-30T23:36:35.940+0000] {subprocess.py:106} INFO - [0m23:36:35  18 of 18 ERROR unique_sales_metrics_date ....................................... [[31mERROR[0m in 0.02s]
[2025-03-30T23:36:35.950+0000] {subprocess.py:106} INFO - [0m23:36:35
[2025-03-30T23:36:35.951+0000] {subprocess.py:106} INFO - [0m23:36:35  Finished running 4 incremental models, 13 data tests, 1 view model in 0 hours 0 minutes and 0.67 seconds (0.67s).
[2025-03-30T23:36:35.980+0000] {subprocess.py:106} INFO - [0m23:36:35
[2025-03-30T23:36:35.980+0000] {subprocess.py:106} INFO - [0m23:36:35  [31mCompleted with 2 errors, 0 partial successes, and 0 warnings:[0m
[2025-03-30T23:36:35.980+0000] {subprocess.py:106} INFO - [0m23:36:35
[2025-03-30T23:36:35.981+0000] {subprocess.py:106} INFO - [0m23:36:35    Database Error in test not_null_sales_metrics_date (models/mart/_mart__schema.yml)
[2025-03-30T23:36:35.981+0000] {subprocess.py:106} INFO -   column "date" does not exist
[2025-03-30T23:36:35.981+0000] {subprocess.py:106} INFO -   LINE 13: select date
[2025-03-30T23:36:35.981+0000] {subprocess.py:106} INFO -                   ^
[2025-03-30T23:36:35.981+0000] {subprocess.py:106} INFO -   compiled code at target/run/hostaway_tht/models/mart/_mart__schema.yml/not_null_sales_metrics_date.sql
[2025-03-30T23:36:35.981+0000] {subprocess.py:106} INFO - [0m23:36:35
[2025-03-30T23:36:35.981+0000] {subprocess.py:106} INFO - [0m23:36:35    Database Error in test unique_sales_metrics_date (models/mart/_mart__schema.yml)
[2025-03-30T23:36:35.982+0000] {subprocess.py:106} INFO -   column "date" does not exist
[2025-03-30T23:36:35.982+0000] {subprocess.py:106} INFO -   LINE 12:     date as unique_field,
[2025-03-30T23:36:35.982+0000] {subprocess.py:106} INFO -                ^
[2025-03-30T23:36:35.982+0000] {subprocess.py:106} INFO -   compiled code at target/run/hostaway_tht/models/mart/_mart__schema.yml/unique_sales_metrics_date.sql
[2025-03-30T23:36:35.982+0000] {subprocess.py:106} INFO - [0m23:36:35
[2025-03-30T23:36:35.982+0000] {subprocess.py:106} INFO - [0m23:36:35  Done. PASS=16 WARN=0 ERROR=2 SKIP=0 TOTAL=18
[2025-03-30T23:36:36.860+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-30T23:36:36.876+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-30T23:36:36.880+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=sales_data, task_id=build_dbt, run_id=manual__2025-03-30T23:35:43.744902+00:00, execution_date=20250330T233543, start_date=20250330T233633, end_date=20250330T233636
[2025-03-30T23:36:36.904+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T23:36:36.904+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 67 for task build_dbt (Bash command failed. The command returned a non-zero exit code 1.; 324)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-30T23:36:36.921+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T23:36:36.943+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T23:36:36.944+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
